name: Android CI - Build APK
on:
  push:
    branches: [ "**" ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
      - name: Install Android platform and build tools
        run: |
          sdkmanager --install "platforms;android-34" "build-tools;34.0.0" "platform-tools" "cmdline-tools;latest"
          yes | sdkmanager --licenses
      - name: Generate Gradle wrapper
        run: |
          gradle wrapper --gradle-version 8.7
          chmod +x gradlew
      - name: Build debug APK
        run: ./gradlew clean assembleDebug
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
          retention-days: 7
